version: '3'

services:
  runserver:
    image: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - migrate
      - celery

  migrate:
    build: ./src
    image: django-app
    command: python manage.py migrate --noinput
    volumes:
      - ./src:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db

  celery:
    image: django-app
    command: celery -A app worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - migrate


  autotests:
    image: django-app
    command: python manage.py test
    env_file:
      - .env
    depends_on:
      - migrate

  demo_pages:
    image: django-app
    command: python manage.py demo_pages
    env_file:
      - .env
    depends_on:
      - migrate

  redis:
    image: redis:3.0-alpine
    command: redis-server
    ports:
      - '6379:6379'

  db:
    image: postgres:12.0
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

volumes:
  pg_data:
